### ISSUE TITLE
Source code for Minecraft 1.16.5

### ISSUE THREAD

**Issue by Nincodedo** [Gerflargle/TaffyDAF#2]
There is a version of this mod on Curse for 1.16.5 but no source code. Could that be added?

**Comment by Gerflargle** [comment]
Hopefully I didn't mess up anything when making a 1.16.5 branch. Hope that works for you.
https://github.com/Gerflargle/TaffyDAF/tree/1.16.5

**Comment by Nincodedo** [comment]
Thank you!
